
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 24 20:36:50 CST 2021
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Coma = 40;
  public static final int End = 19;
  public static final int Llave_c = 13;
  public static final int Llave_a = 12;
  public static final int Entrada = 28;
  public static final int Estructuras_control = 22;
  public static final int Diferente = 38;
  public static final int CX = 35;
  public static final int Estructuras_iteracion = 23;
  public static final int Corchete_c = 26;
  public static final int Corchete_a = 25;
  public static final int Leer = 21;
  public static final int Tipo_dato = 41;
  public static final int Punto = 27;
  public static final int Division = 9;
  public static final int Int = 4;
  public static final int Parentesis_c = 11;
  public static final int Parentesis_a = 10;
  public static final int EOF = 0;
  public static final int P_coma = 16;
  public static final int BX = 36;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int D_puntos = 32;
  public static final int Print = 15;
  public static final int ERROR = 42;
  public static final int Instrucciones = 39;
  public static final int Asm = 33;
  public static final int Identificador = 17;
  public static final int Mod = 24;
  public static final int Librerias = 30;
  public static final int Salida = 29;
  public static final int Resta = 7;
  public static final int T_datos = 3;
  public static final int Escribir = 20;
  public static final int AX = 34;
  public static final int DX = 37;
  public static final int Multiplicacion = 8;
  public static final int Numero = 18;
  public static final int Suma = 6;
  public static final int Main = 14;
  public static final int Igual = 5;
  public static final int Comillas = 31;
}

